<a href="https://colab.research.google.com/github/zafar-farooque/M-L-tutorial/blob/main/multiple_Linear_Regression(ols).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd


In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.datasets import load_diabetes

In [5]:
X,y = load_diabetes(return_X_y=True)

In [16]:
X_train,X_test , y_train, y_test= train_test_split(X,y,test_size=0.2,random_state=2)

In [19]:
X_train

array([[-0.00188202, -0.04464164, -0.06979687, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [-0.00914709, -0.04464164,  0.01103904, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 0.06350368,  0.05068012, -0.00405033, ..., -0.00259226,
         0.08449153, -0.01764613],
       [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 0.00175052,  0.05068012,  0.05954058, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [8]:
y_train.shape

(353,)

In [10]:
X_test.shape

(89, 10)

In [11]:
y_test.shape

(89,)

In [21]:
class MeraLR:
  def __init__(self):
    self.intercept=None
    self.slope= None
  def fit(self, X_train,y_train):
    X_train=np.insert(X_train,0,1,axis=1)
    beta= np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)

    self.intercept= beta[0]
    self.slope  = beta[1:]
    return self.intercept, self.slope
  def predict(self,X_test):
    y_pred= np.dot(X_test, self.slope)+ self.intercept
    return y_pred



In [22]:
lr= MeraLR()


In [23]:
lr.fit(X_train,y_train)

(np.float64(151.88331005254165),
 array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
        -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
         861.12700152,   52.42112238]))

In [27]:
y_pred=lr.predict(X_test)

In [25]:
y_test

array([ 73., 233.,  97., 111., 277., 341.,  64.,  68.,  65., 178., 142.,
        77., 244., 115., 258.,  87., 220.,  86.,  74., 132., 136., 220.,
        91., 235., 148., 317., 131.,  84.,  65., 217., 306.,  79., 158.,
        54., 123., 174., 237., 212., 179., 281., 187., 200.,  68., 163.,
       141., 202., 178., 242.,  47., 131., 243., 142., 200.,  89., 232.,
        55., 253., 128., 104., 184., 110., 198.,  81., 195., 150.,  63.,
       151., 233., 178.,  84., 237., 109., 131., 252., 200., 160., 200.,
        51., 111.,  77., 201.,  88.,  78., 243., 268.,  55., 270., 288.,
        91.])

In [26]:
from sklearn.metrics import r2_score

In [28]:
r2_score(y_test, y_pred)

0.43993386615689634